INSERT INTO users (name, email) VALUES
('Paul', 'paul@gmail.com'),
('John', 'john@yahoo.com'),
('Alice', 'alice@outlook.com'),
('Bob', 'bob@gmail.com'),
('Charlie', 'charlie@yahoo.com'),
('David', 'david@outlook.com'),
('Eve', 'eve@gmail.com'),
('Frank', 'frank@icloud.com'),
('Grace', 'grace@yahoo.com'),
('Hannah', 'hannah@outlook.com'),
('Ivy', 'ivy@gmail.com'),
('Jack', 'jack@live.com'),
('Karen', 'karen@yahoo.com'),
('Leo', 'leo@gmail.com'),
('Mia', 'mia@outlook.com'),
('Nina', 'nina@gmail.com'),
('Oscar', 'oscar@yahoo.com'),
('Pauline', 'pauline@outlook.com'),
('Quinn', 'quinn@gmail.com'),
('Ray', 'ray@icloud.com'),
('Sophie', 'sophie@yahoo.com'),
('Tom', 'tom@outlook.com'),
('Uma', 'uma@gmail.com'),
('Vera', 'vera@live.com'),
('Will', 'will@yahoo.com');

INSERT INTO polls (question, creator_link, poll_link, title1, description1, title2, description2, title3, description3) VALUES
('Where should we eat?', '', '', 'Alfredos', 'Italian', 'Sushi Palace', 'Japanese', 'Burger Haven', ''),
('What movie should we watch?', '', '', 'Inception', 'A mind-bending thriller', 'The Lion King', '', 'The Matrix', 'A sci-fi action film'),
('Which game should we play?', '', '', 'Among Us', '', 'Minecraft', '', 'Monopoly', 'A classic board game'),
('What activity should we do this weekend?', '', '', 'Hiking', '', 'Movie Marathon', 'A series of films back-to-back', 'Picnic', ''),
('Where should we go on vacation?', '', '', 'Hawaii', '', 'Paris', 'The city of love', 'Tokyo', ''),
('What restaurant should we try next?', '', '', 'Olive Garden', 'Italian chain restaurant', 'Red Lobster', '', 'Cheesecake Factory', 'Known for its desserts'),
('Which book should we read for the book club?', '', '', 'The Great Gatsby', '', '1984', 'A dystopian novel by George Orwell', 'Pride and Prejudice', ''),
('What theme should we choose for the party?', '', '', 'Tropical', '', 'Hollywood', 'Red carpet and movie stars', 'Masquerade', ''),
('What time should we meet up?', '', '', '6 PM', '', '7 PM', 'After work hours', '8 PM', ''),
('Which music playlist should we listen to?', '', '', 'Top Hits 2024', '', 'Chill Vibes', 'Relaxing tunes for unwinding', 'Throwback Classics', ''),
('What should be our next group project?', '', '', 'Community Garden', '', 'Charity Fundraiser', 'Support a local cause', 'Art Installation', ''),
('Where should we have our next team outing?', '', '', 'Bowling Alley', '', 'Escape Room', 'Team-building experience', 'Amusement Park', ''),
('What sport should we play together?', '', '', 'Soccer', '', 'Basketball', 'Fast-paced and fun', 'Volleyball', ''),
('Which city should we explore next?', '', '', 'San Francisco', '', 'New Orleans', 'Famous for its vibrant culture', 'Chicago', ''),
('What should we do for the next holiday gathering?', '', '', 'Potluck Dinner', '', 'Secret Santa', 'Gift exchange game', 'Holiday Movie Night', ''),
('Which charity should we support this year?', '', '', 'Local Food Bank', '', 'Animal Shelter', 'Help abandoned pets', 'Environmental Organization', ''),
('What color scheme should we use for the event?', '', '', 'Blue and Gold', '', 'Red and White', 'Classic combination', 'Green and Brown', ''),
('What snack should we bring to the movie night?', '', '', 'Popcorn', 'A movie classic', 'Nachos', '', 'Candy', 'Sweet treats for everyone'),
('Which online course should we take together?', '', '', 'Photography Basics', '', 'Cooking for Beginners', 'Learn to cook simple dishes', 'Web Development', ''),
('What theme should we choose for next months book club?', '', '', 'Mystery', '', 'Science Fiction', 'Explore futuristic worlds', 'Biography', ''),
('What should be our next team-building activity?', '', '', 'Cooking Class', '', 'Outdoor Adventure', 'Explore nature together', 'Team Sports Day', ''),
('Where should we host the next meeting?', '', '', 'Local Cafe', '', 'Office Conference Room', 'Convenient for everyone', 'Park', 'If the weather permits'),
('What should we watch for our next group movie night?', '', '', 'The Avengers', '', 'The Godfather', 'An iconic classic', 'Frozen', ''),
('What should we order for lunch?', '', '', 'Pizza', 'Always a favorite', 'Sushi', '', 'Sandwiches', ''),
('What hobby should we try together?', '', '', 'Painting', 'Get creative with colors', 'Gardening', '', 'Photography', 'Capture moments together');

INSERT INTO poll_creators (user_id, poll_id, creator) VALUES
(1, 1, true),
(1, 2, true),
(1, 3, true),
(1, 4, true),
(1, 5, true),
(1, 6, false),
(1, 7, false),
(1, 8, false),
(1, 9, false),
(1, 10, false),
(1, 11, false),
(1, 12, false),
(1, 13, false),
(1, 14, false),
(1, 15, false),
(1, 16, false),
(1, 17, false),
(1, 18, false),
(1, 19, false),
(1, 20, false),
(1, 21, false),
(1, 22, false),
(1, 23, false),
(1, 24, false),
(1, 25, false),

(2, 1, false),
(2, 2, false),
(2, 3, false),
(2, 4, false),
(2, 5, false),
(2, 6, true),
(2, 7, true),
(2, 8, true),
(2, 9, true),
(2, 10, true),
(2, 11, false),
(2, 12, false),
(2, 13, false),
(2, 14, false),
(2, 15, false),
(2, 16, false),
(2, 17, false),
(2, 18, false),
(2, 19, false),
(2, 20, false),
(2, 21, false),
(2, 22, false),
(2, 23, false),
(2, 24, false),
(2, 25, false),

(3, 1, false),
(3, 2, false),
(3, 3, false),
(3, 4, false),
(3, 5, false),
(3, 6, false),
(3, 7, false),
(3, 8, false),
(3, 9, false),
(3, 10, false),
(3, 11, true),
(3, 12, true),
(3, 13, true),
(3, 14, true),
(3, 15, true),
(3, 16, false),
(3, 17, false),
(3, 18, false),
(3, 19, false),
(3, 20, false),
(3, 21, false),
(3, 22, false),
(3, 23, false),
(3, 24, false),
(3, 25, false),

(4, 1, false),
(4, 2, false),
(4, 3, false),
(4, 4, false),
(4, 5, false),
(4, 6, false),
(4, 7, false),
(4, 8, false),
(4, 9, false),
(4, 10, false),
(4, 11, false),
(4, 12, false),
(4, 13, false),
(4, 14, false),
(4, 15, false),
(4, 16, true),
(4, 17, true),
(4, 18, true),
(4, 19, true),
(4, 20, true),
(4, 21, false),
(4, 22, false),
(4, 23, false),
(4, 24, false),
(4, 25, false),

(5, 1, false),
(5, 2, false),
(5, 3, false),
(5, 4, false),
(5, 5, false),
(5, 6, false),
(5, 7, false),
(5, 8, false),
(5, 9, false),
(5, 10, false),
(5, 11, false),
(5, 12, false),
(5, 13, false),
(5, 14, false),
(5, 15, false),
(5, 16, false),
(5, 17, false),
(5, 18, false),
(5, 19, false),
(5, 20, false),
(5, 21, true),
(5, 22, true),
(5, 23, true),
(5, 24, true),
(5, 25, true);

INSERT INTO responses (respondent_id, poll_id, choice1, choice2, choice3) VALUES
-- responses for poll 1
(1, 1, 'Alfredos', 'Sushi Palace', 'Burger Haven'),
(12, 1, 'Alfredos', 'Burger Haven', 'Sushi Palace'),
(5, 1, 'Sushi Palace', 'Burger Haven', 'Alfredos'),

-- responses for poll 2
(1, 2, 'Inception', 'The Lion King', 'The Matrix'),
(8, 2, 'Inception', 'The Matrix', 'The Lion King'),
(15, 2, 'The Lion King', 'Inception', 'The Matrix'),
(22, 2, 'The Matrix', 'Inception', 'The Lion King'),
(3, 2, 'The Lion King', 'The Matrix', 'Inception'),

-- responses for poll 3
(1, 3, 'Among Us', 'Minecraft', 'Monopoly'),
(5, 3, 'Minecraft', 'Monopoly', 'Among Us'),
(12, 3, 'Monopoly', 'Among Us', 'Minecraft'),
(18, 3, 'Among Us', 'Minecraft', 'Monopoly'),

-- responses for poll 4
(1, 4, 'Hiking', 'Movie Marathon', 'Picnic'),
(9, 4, 'Picnic', 'Hiking', 'Movie Marathon'),
(15, 4, 'Movie Marathon', 'Picnic', 'Hiking'),

-- responses for poll 5
(1, 5, 'Hawaii', 'Paris', 'Tokyo'),
(3, 5, 'Paris', 'Tokyo', 'Hawaii'),
(7, 5, 'Tokyo', 'Hawaii', 'Paris'),
(11, 5, 'Hawaii', 'Tokyo', 'Paris'),
(14, 5, 'Paris', 'Hawaii', 'Tokyo'),
(19, 5, 'Tokyo', 'Paris', 'Hawaii'),

-- responses for poll 6
(2, 6, 'Olive Garden', 'Red Lobster', 'Cheesecake Factory'),
(4, 6, 'Red Lobster', 'Cheesecake Factory', 'Olive Garden'),
(9, 6, 'Cheesecake Factory', 'Olive Garden', 'Red Lobster'),
(16, 6, 'Olive Garden', 'Cheesecake Factory', 'Red Lobster'),

-- responses for poll 7
(2, 7, 'The Great Gatsby', '1984', 'Pride and Prejudice'),
(5, 7, 'Pride and Prejudice', '1984', 'The Great Gatsby'),

-- responses for poll 8
(2, 8, 'Tropical', 'Hollywood', 'Masquerade'),
(4, 8, 'Masquerade', 'Tropical', 'Hollywood'),
(8, 8, 'Hollywood', 'Masquerade', 'Tropical'),
(15, 8, 'Tropical', 'Hollywood', 'Masquerade'),
(20, 8, 'Hollywood', 'Tropical', 'Masquerade'),

-- responses for poll 9
(2, 9, '6 PM', '7 PM', '8 PM'),
(5, 9, '7 PM', '8 PM', '6 PM'),
(12, 9, '8 PM', '6 PM', '7 PM'),

-- responses for poll 10
(2, 10, 'Top Hits 2024', 'Chill Vibes', 'Throwback Classics'),
(3, 10, 'Chill Vibes', 'Throwback Classics', 'Top Hits 2024'),
(7, 10, 'Throwback Classics', 'Top Hits 2024', 'Chill Vibes'),
(15, 10, 'Top Hits 2024', 'Throwback Classics', 'Chill Vibes'),

-- responses for poll 11
(3, 11, 'Community Garden', 'Charity Fundraiser', 'Art Installation'),
(5, 11, 'Art Installation', 'Community Garden', 'Charity Fundraiser'),
(10, 11, 'Charity Fundraiser', 'Art Installation', 'Community Garden'),
(14, 11, 'Community Garden', 'Charity Fundraiser', 'Art Installation'),
(17, 11, 'Art Installation', 'Community Garden', 'Charity Fundraiser'),
(20, 11, 'Charity Fundraiser', 'Community Garden', 'Art Installation'),
(25, 11, 'Community Garden', 'Art Installation', 'Charity Fundraiser'),

-- responses for poll 12
(3, 12, 'Bowling Alley', 'Escape Room', 'Amusement Park'),
(6, 12, 'Escape Room', 'Amusement Park', 'Bowling Alley'),
(11, 12, 'Amusement Park', 'Bowling Alley', 'Escape Room'),

-- responses for poll 13
(3, 13, 'Soccer', 'Basketball', 'Volleyball'),
(7, 13, 'Basketball', 'Volleyball', 'Soccer'),
(10, 13, 'Volleyball', 'Soccer', 'Basketball'),
(15, 13, 'Soccer', 'Volleyball', 'Basketball'),

-- responses for poll 14
(3, 14, 'San Francisco', 'New Orleans', 'Chicago'),
(6, 14, 'New Orleans', 'Chicago', 'San Francisco'),
(11, 14, 'Chicago', 'San Francisco', 'New Orleans'),
(16, 14, 'San Francisco', 'Chicago', 'New Orleans'),
(22, 14, 'New Orleans', 'San Francisco', 'Chicago'),

-- responses for poll 15
(3, 15, 'Potluck Dinner', 'Secret Santa', 'Holiday Movie Night'),
(5, 15, 'Secret Santa', 'Holiday Movie Night', 'Potluck Dinner'),
(9, 15, 'Holiday Movie Night', 'Potluck Dinner', 'Secret Santa'),
(14, 15, 'Potluck Dinner', 'Holiday Movie Night', 'Secret Santa'),
(18, 15, 'Secret Santa', 'Potluck Dinner', 'Holiday Movie Night'),
(25, 15, 'Holiday Movie Night', 'Secret Santa', 'Potluck Dinner'),

-- responses for poll 16
(4, 16, 'Local Food Bank', 'Animal Shelter', 'Environmental Organization'),
(7, 16, 'Animal Shelter', 'Environmental Organization', 'Local Food Bank'),
(12, 16, 'Environmental Organization', 'Local Food Bank', 'Animal Shelter'),

-- responses for poll 17
(4, 17, 'Blue and Gold', 'Red and White', 'Green and Brown'),
(8, 17, 'Red and White', 'Green and Brown', 'Blue and Gold'),
(10, 17, 'Green and Brown', 'Blue and Gold', 'Red and White'),
(15, 17, 'Blue and Gold', 'Red and White', 'Green and Brown'),
(21, 17, 'Red and White', 'Green and Brown', 'Blue and Gold'),

-- responses for poll 18
(4, 18, 'Popcorn', 'Nachos', 'Candy'),
(6, 18, 'Nachos', 'Candy', 'Popcorn'),
(11, 18, 'Candy', 'Popcorn', 'Nachos'),
(16, 18, 'Popcorn', 'Candy', 'Nachos'),

-- responses for poll 19
(4, 19, 'Photography Basics', 'Cooking for Beginners', 'Web Development'),
(5, 19, 'Cooking for Beginners', 'Web Development', 'Photography Basics'),
(9, 19, 'Web Development', 'Photography Basics', 'Cooking for Beginners'),

-- responses for poll 20
(4, 20, 'Mystery', 'Science Fiction', 'Biography'),
(1, 20, 'Science Fiction', 'Biography', 'Mystery'),
(7, 20, 'Biography', 'Mystery', 'Science Fiction'),
(10, 20, 'Mystery', 'Science Fiction', 'Biography'),
(12, 20, 'Biography', 'Mystery', 'Science Fiction'),
(15, 20, 'Science Fiction', 'Biography', 'Mystery'),
(18, 20, 'Mystery', 'Biography', 'Science Fiction'),
(21, 20, 'Biography', 'Science Fiction', 'Mystery'),

-- responses for poll 21
(5, 21, 'Cooking Class', 'Outdoor Adventure', 'Team Sports Day'),
(2, 21, 'Outdoor Adventure', 'Team Sports Day', 'Cooking Class'),
(8, 21, 'Team Sports Day', 'Cooking Class', 'Outdoor Adventure'),
(11, 21, 'Cooking Class', 'Team Sports Day', 'Outdoor Adventure'),
(14, 21, 'Outdoor Adventure', 'Cooking Class', 'Team Sports Day'),
(19, 21, 'Team Sports Day', 'Outdoor Adventure', 'Cooking Class'),

-- responses for poll 22
(5, 22, 'Local Cafe', 'Office Conference Room', 'Park'),
(3, 22, 'Park', 'Local Cafe', 'Office Conference Room'),
(9, 22, 'Office Conference Room', 'Park', 'Local Cafe'),
(12, 22, 'Local Cafe', 'Park', 'Office Conference Room'),
(16, 22, 'Park', 'Office Conference Room', 'Local Cafe'),

-- responses for poll 23
(5, 23, 'The Avengers', 'The Godfather', 'Frozen'),
(2, 23, 'Frozen', 'The Godfather', 'The Avengers'),
(8, 23, 'The Godfather', 'Frozen', 'The Avengers'),
(12, 23, 'The Avengers', 'Frozen', 'The Godfather'),

-- responses for poll 24
(5, 24, 'Pizza', 'Sushi', 'Sandwiches'),
(3, 24, 'Sushi', 'Sandwiches', 'Pizza'),
(7, 24, 'Sandwiches', 'Pizza', 'Sushi'),

-- responses for poll 25
(5, 25, 'Painting', 'Gardening', 'Photography'),
(2, 25, 'Gardening', 'Photography', 'Painting'),
(8, 25, 'Photography', 'Painting', 'Gardening'),
(12, 25, 'Painting', 'Gardening', 'Photography'),
(15, 25, 'Gardening', 'Painting', 'Photography'),
(18, 25, 'Photography', 'Gardening', 'Painting'),
(22, 25, 'Painting', 'Photography', 'Gardening');
