DROP TABLE IF EXISTS responses;
DROP TABLE IF EXISTS poll_creators;
DROP TABLE IF EXISTS polls;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
 id SERIAL PRIMARY KEY NOT NULL,
 name VARCHAR(255) NOT NULL,
 email VARCHAR(255) NOT NULL
);

CREATE TABLE polls (
  id SERIAL PRIMARY KEY NOT NULL,
  question TEXT NOT NULL,
  creator_link TEXT,
  poll_link TEXT,
  title1 TEXT NOT NULL,
  description1 TEXT,
  title2 TEXT NOT NULL,
  description2 TEXT,
  title3 TEXT NOT NULL,
  description3 TEXT
);

CREATE TABLE poll_creators (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  poll_id INTEGER REFERENCES polls(id) ON DELETE CASCADE,
  creator BOOLEAN DEFAULT FALSE
);

CREATE TABLE responses (
  id SERIAL PRIMARY KEY NOT NULL,
  respondent_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  poll_id INTEGER REFERENCES polls(id) ON DELETE CASCADE,
  choice1 TEXT NOT NULL,
  choice2 TEXT NOT NULL,
  choice3 TEXT NOT NULL
  );
